name: Deploy

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

env:
  UNIT: bot
  WORKDIR: /Users/narumi/services/bot
  PLIST_DIR: /Users/narumi/Library/LaunchAgents

jobs:
  deploy:
    runs-on: self-hosted
    strategy:
      matrix:
        python-version: ["3.13"]
    steps:
      - uses: actions/checkout@v6
      - name: Stop and disable service
        continue-on-error: true
        working-directory: ${{ env.PLIST_DIR }}
        run: |
          launchctl stop ${{ env.UNIT }}
          launchctl unload bot.plist
      - name: Create dotenv
        run: |
          <<'EOF' > .env
          BOT_TOKEN=${{ secrets.BOT_TOKEN }}
          BOT_WHITELIST=${{ vars.BOT_WHITELIST }}
          OPENAI_MODEL=${{ vars.OPENAI_MODEL }}
          OPENAI_BASE_URL=${{ vars.OPENAI_BASE_URL }}
          LITELLM_API_KEY=${{ secrets.LITELLM_API_KEY }}
          LOGFIRE_TOKEN=${{ secrets.LOGFIRE_TOKEN }}
          LOGFIRE_ENVIRONMENT=prod
          FFMPEG_PATH=/opt/homebrew/bin/ffmpeg
          FIRECRAWL_API_KEY=${{ secrets.FIRECRAWL_API_KEY }}
          EOF
      - name: Copy files
        run: |
          rm -rf ${{ env.WORKDIR }}
          cp -rf ${{ github.workspace }} ${{ env.WORKDIR }}
          cp bot.plist ${{ env.PLIST_DIR }}
      - name: Install dependencies
        run: |
          uv venv --clear --managed-python --python ${{ matrix.python-version }}
          uv sync
          uv run playwright install chromium
      - name: Start service
        working-directory: ${{ env.PLIST_DIR }}
        run: |
          launchctl load -w bot.plist
          launchctl start ${{ env.UNIT }}
