name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  UNIT: bot
  WORKDIR: /Users/narumi/services/bot
  PLIST_DIR: /Users/narumi/Library/LaunchAgents

jobs:
  deploy:
    runs-on: self-hosted
    strategy:
      matrix:
        python-version: ["3.13"]
    steps:
      - uses: actions/checkout@v6
      - name: Stop and disable service
        continue-on-error: true
        working-directory: ${{ env.PLIST_DIR }}
        run: |
          launchctl stop ${{ env.UNIT }}
          launchctl unload bot.plist
      - name: Install dependencies
        run: |
          uv venv --clear --managed-python --python ${{ matrix.python-version }}
          uv sync --upgrade
          uv run playwright install chromium
      - name: Create dotenv
        run: |
          echo BOT_TOKEN=${{ secrets.BOT_TOKEN }} >> .env
          echo BOT_WHITELIST=${{ vars.BOT_WHITELIST }} >> .env
          echo OPENAI_MODEL=${{ vars.OPENAI_MODEL }} >> .env
          echo OPENAI_BASE_URL=${{ vars.OPENAI_BASE_URL }} >> .env
          echo LITELLM_API_KEY=${{ secrets.LITELLM_API_KEY }} >> .env
          echo LOGFIRE_TOKEN=${{ secrets.LOGFIRE_TOKEN }} >> .env
          echo LOGFIRE_ENVIRONMENT=prod >> .env
          echo LANGFUSE_SECRET_KEY=${{ secrets.LANGFUSE_SECRET_KEY }} >> .env
          echo LANGFUSE_PUBLIC_KEY=${{ secrets.LANGFUSE_PUBLIC_KEY }} >> .env
          echo LANGFUSE_HOST=${{ vars.LANGFUSE_HOST }} >> .env
          echo FFMPEG_PATH=/opt/homebrew/bin/ffmpeg >> .env
          echo FIRECRAWL_API_KEY=${{ secrets.FIRECRAWL_API_KEY }} >> .env
      - name: Copy files
        run: |
          rm -rf ${{ env.WORKDIR }}
          cp -rf ${{ github.workspace }} ${{ env.WORKDIR }}
          cp bot.plist ${{ env.PLIST_DIR }}
      - name: Start service
        working-directory: ${{ env.PLIST_DIR }}
        run: |
          launchctl load -w bot.plist
          launchctl start ${{ env.UNIT }}
