name: Deploy

on:
  workflow_dispatch:
  # push:
  #   tags:
  #     - "v*.*.*"

env:
  UNIT: bot
  WORKDIR: /Users/narumi/apps/bot
  PLIST_DIR: /Users/narumi/Library/LaunchAgents

jobs:
  deploy:
    runs-on: self-hosted
    strategy:
      matrix:
        python-version: ["3.13"]
    steps:
      - uses: actions/checkout@v6
      - name: Sync code to runtime
        shell: bash
        run: |
          rsync -a --delete \
            --filter=':- .gitignore' \
            --exclude='.venv/' \
            ${{ github.workspace }}/ ${{ env.WORKDIR }}/
      - name: Stop and disable service
        continue-on-error: true
        working-directory: ${{ env.PLIST_DIR }}
        run: |
          launchctl stop ${{ env.UNIT }}
          launchctl unload bot.plist
      - name: Create dotenv
        working-directory: ${{ env.WORKDIR }}
        run: |
          cat <<'EOF' > .env
          BOT_TOKEN=${{ secrets.BOT_TOKEN }}
          BOT_WHITELIST=${{ vars.BOT_WHITELIST }}
          OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
          # OPENAI_MODEL=${{ vars.OPENAI_MODEL }}
          # OPENAI_BASE_URL=${{ vars.OPENAI_BASE_URL }}
          # LITELLM_API_KEY=${{ secrets.LITELLM_API_KEY }}
          LOGFIRE_TOKEN=${{ secrets.LOGFIRE_TOKEN }}
          LOGFIRE_ENVIRONMENT=prod
          FFMPEG_PATH=/opt/homebrew/bin/ffmpeg
          FIRECRAWL_API_KEY=${{ secrets.FIRECRAWL_API_KEY }}
          SERPAPI_API_KEY=${{ secrets.SERPAPI_API_KEY }}
          EOF
      - name: Preparing environment
        working-directory: ${{ env.WORKDIR }}
        run: |
          cp bot.plist ${{ env.PLIST_DIR }}
          # uv venv --clear --managed-python --python ${{ matrix.python-version }}
          rm -rf .venv
          uv sync
          uv run playwright install chromium
      - name: Start service
        working-directory: ${{ env.PLIST_DIR }}
        run: |
          launchctl load -w bot.plist
          launchctl start ${{ env.UNIT }}
